import { accentStudies, deRochePrimitives as dr, deRocheWavePalette as wave, type SemanticColorTokens } from '../foundations/colors';

const accent = accentStudies.earthDigitalDual;

export const deRocheNightTheme = {
  id: 'de-roche-night',
  name: 'De Roche Night',
  mode: 'dark',
  balance: '65% carbon/charcoal/basalt, 20% stone/earth, 10% bone/beige, 5% accent/audio',
  colors: {
    backgroundPrimary: dr.black950,
    backgroundSecondary: dr.black900,
    backgroundElevated: dr.charcoal850,
    backgroundRecessed: '#070706',
    backgroundInverse: dr.paper100,
    surfacePrimary: dr.charcoal850,
    surfaceSecondary: dr.charcoal800,
    surfaceHover: dr.basalt750,
    surfaceActive: dr.stone700,
    surfaceSelected: '#2F2C25',
    surfaceDisabled: '#201F1B',
    textPrimary: dr.chalk150,
    textSecondary: dr.bone200,
    textTertiary: dr.beige400,
    textInverse: dr.black900,
    textDisabled: dr.taupe550,
    borderSubtle: '#24231E',
    borderDefault: dr.basalt750,
    borderStrong: dr.stone700,
    borderFocus: accent.brandPrimary,
    brandPrimary: accent.brandPrimary,
    brandPrimaryHover: accent.brandPrimaryHover,
    brandPrimaryActive: accent.brandPrimaryActive,
    brandOnPrimary: accent.brandOnPrimary,
    waveLow: wave.sub,
    waveLowMid: wave.lowMid,
    waveMid: wave.mid,
    waveHighMid: wave.highMid,
    waveHigh: wave.high,
    success: '#6FA58A',
    warning: '#C88B46',
    error: '#D66738',
    information: '#71A4B5',
  } satisfies SemanticColorTokens,
} as const;
