import { accentStudies, deRochePrimitives as dr, deRocheWavePalette as wave, type SemanticColorTokens } from '../foundations/colors';

const accent = accentStudies.luxuryBeige;

export const deRocheArchiveTheme = {
  id: 'de-roche-archive',
  name: 'De Roche Archive',
  mode: 'light',
  balance: 'printed catalogue paper with carbon separators and warm stone surfaces',
  colors: {
    backgroundPrimary: dr.paper100,
    backgroundSecondary: dr.chalk150,
    backgroundElevated: dr.bone200,
    backgroundRecessed: dr.limestone300,
    backgroundInverse: dr.black950,
    surfacePrimary: dr.chalk150,
    surfaceSecondary: dr.bone200,
    surfaceHover: dr.limestone300,
    surfaceActive: dr.sand350,
    surfaceSelected: '#D1C5B5',
    surfaceDisabled: '#D8D0C3',
    textPrimary: dr.black900,
    textSecondary: dr.earth650,
    textTertiary: dr.taupe550,
    textInverse: dr.paper100,
    textDisabled: dr.stone500,
    borderSubtle: '#D2C7B8',
    borderDefault: dr.limestone300,
    borderStrong: dr.taupe550,
    borderFocus: dr.black900,
    brandPrimary: accent.brandPrimary,
    brandPrimaryHover: accent.brandPrimaryHover,
    brandPrimaryActive: accent.brandPrimaryActive,
    brandOnPrimary: accent.brandOnPrimary,
    waveLow: wave.sub,
    waveLowMid: wave.lowMid,
    waveMid: wave.mid,
    waveHighMid: wave.highMid,
    waveHigh: wave.high,
    success: '#557B65',
    warning: '#9B6B34',
    error: '#A9412D',
    information: '#3C78A8',
  } satisfies SemanticColorTokens,
} as const;
