#!/usr/bin/env bash
#
# Concatenate migrations into ONE file to paste into the Supabase SQL editor,
# for when `npm run db:migrate` (psql) is not available.
#
#   scripts/ops/bundle-migrations.sh 112 113 115 116 121 122 123 > bundle.sql
#
# Each argument is a migration NUMBER; every file with that number is
# included (117/118 have two). Every migration is idempotent, so including one
# that is already applied is harmless, and re-running the whole bundle after a
# failure is safe. The last statement is a read-only check whose result the
# SQL editor shows.
#
# The SQL editor does not keep one session across a pasted script, so a
# migration that creates a TEMP table and reads it in a later statement fails
# there ("relation _paid_buyers does not exist"). Such a migration needs a
# same-effect form in supabase/apply/editor/<same file name>, which is used
# instead; the script refuses to bundle a TEMP-table migration without one.
#
# Paste the WHOLE file and run it with nothing selected — the SQL editor runs
# only the highlighted text when something is selected, which is how a
# half-pasted CREATE TABLE fails with `syntax error at or near "created_at"`.

set -euo pipefail
DIR="$(cd "$(dirname "$0")/../../supabase/migrations" && pwd)"
[ $# -gt 0 ] || { echo "usage: $0 NNN [NNN…]" >&2; exit 1; }

echo "-- Generated by scripts/ops/bundle-migrations.sh on $(date -u +%Y-%m-%d)."
echo "-- Paste ALL of it into Supabase → SQL editor and press Run with nothing selected."
echo "-- An error stops the run. Everything is idempotent: fix the cause, then run the whole file again."
echo
echo "BEGIN;"
for n in "$@"; do
  shopt -s nullglob
  files=("$DIR"/"$n"_*.sql)
  [ ${#files[@]} -gt 0 ] || { echo "no migration numbered $n" >&2; exit 1; }
  for f in "${files[@]}"; do
    editor="$DIR/../apply/editor/$(basename "$f")"
    if [ -f "$editor" ]; then
      src="$editor"
    elif grep -qi 'CREATE TEMP' "$f"; then
      echo "$(basename "$f") uses a TEMP table; add supabase/apply/editor/$(basename "$f")" >&2
      exit 1
    else
      src="$f"
    fi
    echo
    echo "-- ═════════════ $(basename "$f")$([ "$src" = "$editor" ] && echo ' (SQL-editor form)') ═════════════"
    cat "$src"
    echo
  done
done
echo
echo "COMMIT;"
echo
echo "-- ═════════════ check ═════════════"
cat "$DIR/../apply/verify.sql"
