/**
 * Writes a SQL file that checks the REAL `public.has_org_cap` against
 * `capabilitiesFor()` (src/lib/labelos/capabilities.ts, the source of truth).
 *
 * Run by scripts/local-db/check.sh against its throwaway database:
 *   npx jiti scripts/local-db/capability-parity.ts <out.sql>
 *
 * One org + one member per fixture (kind × role × function set × overrides,
 * including values the model does not know), then every capability plus an
 * unknown one is asked of has_org_cap as that member. The file raises if any
 * answer differs. capabilities.sql.test.ts checks the same mapping in CI
 * without Postgres; this is the half that executes the plpgsql itself.
 */
import { writeFileSync } from 'node:fs';
import {
  ALL_CAPABILITIES,
  ORG_FUNCTIONS,
  ORG_KINDS,
  ROLES,
  capabilitiesFor,
  type CapabilityOverrides,
} from '../../src/lib/labelos/capabilities';

const out = process.argv[2];
if (!out) throw new Error('usage: capability-parity.ts <out.sql>');

const OVERRIDES: CapabilityOverrides[] = [
  {},
  { grant: ['rights.write'] },
  { grant: ['members.manage', 'org.manage', 'contracts.read', 'business.read.internal'] },
  { revoke: ['catalog.read'] },
  { revoke: ['rights.read.own_line'] },
  { grant: ['release.write'], revoke: ['release.write'] },
  { grant: ['not.a.cap'], revoke: ['review.comment'] },
];
const FUNCTION_SETS: string[][] = [
  [],
  ['bogus'],
  ...ORG_FUNCTIONS.map((f) => [f]),
  ['a_and_r', 'legal'],
  [...ORG_FUNCTIONS],
];
const CAPS = [...ALL_CAPABILITIES, 'bogus.cap'];

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: readonly string[] = []) => `ARRAY[${xs.map(lit).join(',')}]::text[]`;
const uuid = (prefix: string, n: number) => `${prefix}-0000-4000-8000-${String(n).padStart(12, '0')}`;

const setup: string[] = [];
const expected: string[] = [];
let n = 0;
for (const kind of ORG_KINDS) {
  for (const role of ROLES) {
    for (const functions of FUNCTION_SETS) {
      for (const overrides of OVERRIDES) {
        n++;
        const org = uuid('0a000000', n);
        const user = uuid('0b000000', n);
        setup.push(
          `INSERT INTO auth.users (id) VALUES ('${user}');`,
          `INSERT INTO public.organizations (id, name, slug, kind) VALUES ('${org}', 'parity', 'parity-${n}', ${lit(kind)});`,
          // role `artist` must be artist-scoped (org_members_artist_is_scoped)
          `INSERT INTO public.org_members (org_id, user_id, role, functions, scope, cap_grants, cap_revokes) VALUES ` +
            `('${org}', '${user}', ${lit(role)}, ${arr(functions)}, ${lit(role === 'artist' ? 'artists' : 'org')}, ` +
            `${arr(overrides.grant ?? [])}, ${arr(overrides.revoke ?? [])});`,
        );
        const caps = capabilitiesFor(kind, role, functions, overrides);
        for (const cap of CAPS) {
          expected.push(`('${user}', '${org}', ${lit(cap)}, ${caps.has(cap as never)})`);
        }
      }
    }
  }
}

writeFileSync(
  out,
  `-- generated by scripts/local-db/capability-parity.ts
BEGIN;
${setup.join('\n')}
CREATE TEMP TABLE parity_expected (user_id uuid, org_id uuid, cap text, want boolean);
INSERT INTO parity_expected VALUES
${expected.join(',\n')};
DO $$
DECLARE r record; got boolean; bad int := 0; total int := 0;
BEGIN
  FOR r IN SELECT * FROM parity_expected LOOP
    PERFORM set_config('request.jwt.claims', json_build_object('sub', r.user_id)::text, true);
    got := public.has_org_cap(r.org_id, r.cap);
    total := total + 1;
    IF got IS DISTINCT FROM r.want THEN
      bad := bad + 1;
      IF bad <= 10 THEN
        RAISE WARNING 'parity mismatch: member % cap % — has_org_cap=% capabilitiesFor=%', r.user_id, r.cap, got, r.want;
      END IF;
    END IF;
  END LOOP;
  IF bad > 0 THEN
    RAISE EXCEPTION 'has_org_cap disagrees with capabilitiesFor on % of % checks', bad, total;
  END IF;
  RAISE NOTICE 'capability parity: % checks, 0 mismatches', total;
END $$;
ROLLBACK;
`,
);
console.log(`capability-parity: ${n} members, ${expected.length} checks → ${out}`);
