-- Generated by scripts/ops/bundle-migrations.sh on 2026-09-29.
-- Paste ALL of it into Supabase → SQL editor and press Run with nothing selected.
-- An error stops the run. Everything is idempotent: fix the cause, then run the whole file again.

BEGIN;

-- ═════════════ 130_artist_messages.sql ═════════════
-- 130_artist_messages.sql
-- Artist Relationship Workspace, phase 3: messages and requests.
--
-- Portal comments (mig 128) hang off a project or a beat. What was missing is
-- the plain conversation between the producer and one artist — "are you in
-- town next week?" — and a way for the artist to ASK for something ("send me
-- something darker"). Both are rows here, one thread per contact:
--
--   author        who wrote it: the producer (dashboard) or the artist (portal).
--   kind          'message', or 'request' — only an artist writes a request.
--   request_status open → done / declined, set by the producer. NULL for a
--                 message; the check below keeps the two in step.
--   project_id    optional: the project a request is about.
--   read_at       when the OTHER side saw it (portal load for a producer
--                 message, the workspace thread for an artist message).
--   emailed_at    when a producer message was also emailed to the artist
--                 (lib/artist-messages/email-fallback decides).

CREATE TABLE IF NOT EXISTS public.artist_messages (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  contact_id     uuid NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
  project_id     uuid REFERENCES public.projects(id) ON DELETE SET NULL,
  author         text NOT NULL,
  kind           text NOT NULL DEFAULT 'message',
  body           text NOT NULL,
  request_status text,
  resolved_at    timestamptz,
  read_at        timestamptz,
  emailed_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artist_messages_author_check') THEN
    ALTER TABLE public.artist_messages ADD CONSTRAINT artist_messages_author_check
      CHECK (author IN ('producer', 'artist'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artist_messages_kind_check') THEN
    ALTER TABLE public.artist_messages ADD CONSTRAINT artist_messages_kind_check
      CHECK (kind IN ('message', 'request'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artist_messages_request_check') THEN
    ALTER TABLE public.artist_messages ADD CONSTRAINT artist_messages_request_check
      CHECK (
        (kind = 'message' AND request_status IS NULL)
        OR (kind = 'request' AND author = 'artist' AND request_status IN ('open', 'done', 'declined'))
      );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'artist_messages_body_check') THEN
    ALTER TABLE public.artist_messages ADD CONSTRAINT artist_messages_body_check
      CHECK (char_length(btrim(body)) BETWEEN 1 AND 4000);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_artist_messages_contact ON public.artist_messages (contact_id, created_at);
CREATE INDEX IF NOT EXISTS idx_artist_messages_user ON public.artist_messages (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_artist_messages_open_requests
  ON public.artist_messages (user_id, contact_id) WHERE kind = 'request' AND request_status = 'open';

-- The contact (and the project, when set) must belong to the row's owner.
CREATE OR REPLACE FUNCTION public.artist_messages_same_owner()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.contacts c WHERE c.id = NEW.contact_id AND c.user_id = NEW.user_id) THEN
    RAISE EXCEPTION 'artist_messages: contact % is not owned by %', NEW.contact_id, NEW.user_id;
  END IF;
  IF NEW.project_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.projects p WHERE p.id = NEW.project_id AND p.user_id = NEW.user_id
  ) THEN
    RAISE EXCEPTION 'artist_messages: project % is not owned by %', NEW.project_id, NEW.user_id;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS artist_messages_same_owner ON public.artist_messages;
CREATE TRIGGER artist_messages_same_owner
  BEFORE INSERT OR UPDATE OF user_id, contact_id, project_id ON public.artist_messages
  FOR EACH ROW EXECUTE FUNCTION public.artist_messages_same_owner();

-- Owner-only. The portal reads and writes through the service role after the
-- token gate.
ALTER TABLE public.artist_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS artist_messages_owner_select ON public.artist_messages;
CREATE POLICY artist_messages_owner_select ON public.artist_messages
  FOR SELECT USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS artist_messages_owner_write ON public.artist_messages;
CREATE POLICY artist_messages_owner_write ON public.artist_messages
  FOR ALL USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id AND (SELECT public.is_producer()));

NOTIFY pgrst, 'reload schema';


-- ═════════════ 131_portal_sign_in.sql ═════════════
-- 131_portal_sign_in.sql
-- Artist Relationship Workspace, phase 3: optional email sign-in for a portal.
--
-- A portal link is a bearer credential: anyone the artist forwards it to gets
-- in. The producer can now require the artist to confirm their email first.
-- The portal then emails a short-lived sign-in link to the address ON THE
-- CONTACT (the visitor never types one, so it cannot be pointed elsewhere),
-- and opening it leaves a signed cookie for that browser
-- (lib/artist-portal/sign-in). No Supabase auth user is created: artists are
-- not buyers and not producers.
--
-- sign_in_sent_at throttles the email (one a minute per portal).

ALTER TABLE public.artist_portals
  ADD COLUMN IF NOT EXISTS require_sign_in boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS sign_in_sent_at timestamptz;

NOTIFY pgrst, 'reload schema';


-- ═════════════ 132_song_beats.sql ═════════════
-- 132_song_beats.sql
-- Artist Relationship Workspace, phase 3: a song built on several beats.
--
-- Mig 124 gave a song one pointer, tracks.beat_track_id (its MAIN beat), and
-- said a join table could come later without breaking it. This is that table.
-- tracks.beat_track_id stays and stays the main beat — the app keeps it equal
-- to position 0 here — so everything that reads it keeps working.
--
-- Backfilled from beat_track_id, idempotently.

CREATE TABLE IF NOT EXISTS public.song_beats (
  song_track_id uuid NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
  beat_track_id uuid NOT NULL REFERENCES public.tracks(id) ON DELETE CASCADE,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  position      integer NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (song_track_id, beat_track_id)
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'song_beats_not_self') THEN
    ALTER TABLE public.song_beats ADD CONSTRAINT song_beats_not_self
      CHECK (song_track_id <> beat_track_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_song_beats_beat ON public.song_beats (beat_track_id);
CREATE INDEX IF NOT EXISTS idx_song_beats_user ON public.song_beats (user_id);

-- Song and beat must both belong to the row's owner.
CREATE OR REPLACE FUNCTION public.song_beats_same_owner()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.tracks t WHERE t.id = NEW.song_track_id AND t.user_id = NEW.user_id) THEN
    RAISE EXCEPTION 'song_beats: song % is not owned by %', NEW.song_track_id, NEW.user_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.tracks t WHERE t.id = NEW.beat_track_id AND t.user_id = NEW.user_id) THEN
    RAISE EXCEPTION 'song_beats: beat % is not owned by %', NEW.beat_track_id, NEW.user_id;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS song_beats_same_owner ON public.song_beats;
CREATE TRIGGER song_beats_same_owner
  BEFORE INSERT OR UPDATE ON public.song_beats
  FOR EACH ROW EXECUTE FUNCTION public.song_beats_same_owner();

ALTER TABLE public.song_beats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS song_beats_owner_select ON public.song_beats;
CREATE POLICY song_beats_owner_select ON public.song_beats
  FOR SELECT USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS song_beats_owner_write ON public.song_beats;
CREATE POLICY song_beats_owner_write ON public.song_beats
  FOR ALL USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id AND (SELECT public.is_producer()));

-- Backfill: every existing main beat becomes position 0.
INSERT INTO public.song_beats (song_track_id, beat_track_id, user_id, position)
SELECT s.id, s.beat_track_id, s.user_id, 0
FROM public.tracks s
JOIN public.tracks b ON b.id = s.beat_track_id AND b.user_id = s.user_id
WHERE s.beat_track_id IS NOT NULL AND s.user_id IS NOT NULL
ON CONFLICT (song_track_id, beat_track_id) DO NOTHING;

NOTIFY pgrst, 'reload schema';


COMMIT;

-- ═════════════ check ═════════════
-- Read-only: which pending migrations are in effect on this database.
-- Run it on its own any time; the bundle also ends with it.
SELECT m.migration,
       CASE WHEN m.ok THEN 'applied' ELSE 'MISSING' END AS status
FROM (VALUES
  ('112_backfill_buyer_contacts',    NOT EXISTS (
     SELECT 1 FROM public.license_purchases lp
     WHERE lp.status = 'paid' AND lp.seller_user_id IS NOT NULL AND lp.buyer_email IS NOT NULL
       AND lower(btrim(lp.buyer_email)) <> 'unknown@invalid' AND position('@' in lp.buyer_email) > 1
       AND NOT EXISTS (SELECT 1 FROM public.contacts c WHERE c.user_id = lp.seller_user_id AND lower(btrim(c.email)) = lower(btrim(lp.buyer_email))))),
  ('113_store_layout',               EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'creator_profiles' AND column_name = 'store_layout')),
  ('115_track_collaborators',        to_regclass('public.track_collaborators') IS NOT NULL),
  ('116_notifications_realtime',     EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'notifications')),
  ('121_share_full_playback',        EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'project_shares' AND column_name = 'full_playback')),
  ('122_project_contacts',           to_regclass('public.project_contacts') IS NOT NULL),
  ('123_contact_track_states',       to_regclass('public.contact_track_states') IS NOT NULL),
  ('124_song_beat_and_credit_links', EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tracks' AND column_name = 'beat_track_id')),
  ('125_artist_portals',             to_regclass('public.artist_portals') IS NOT NULL),
  ('126_project_shares_contact',     EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'project_shares' AND column_name = 'contact_id')),
  ('127_project_assets',             to_regclass('public.project_assets') IS NOT NULL),
  ('128_portal_comments',            EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'project_comments' AND column_name = 'contact_id')),
  ('129_artist_portal_auto_digest',  EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'artist_portals' AND column_name = 'auto_digest')),
  ('130_artist_messages',            to_regclass('public.artist_messages') IS NOT NULL),
  ('131_portal_sign_in',             EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'artist_portals' AND column_name = 'require_sign_in')),
  ('132_song_beats',                 to_regclass('public.song_beats') IS NOT NULL)
) AS m(migration, ok)
ORDER BY m.migration;
