import { NextRequest, NextResponse } from 'next/server';
import { requireUser } from '@/lib/auth/ownership';
import { uploadImage } from '@/lib/storage/upload';
import { errorMessage } from '@/lib/errors';
import { createLogger } from '@/lib/log';
import {
  buildCoverPrompt,
  availableProviders,
  resolveProvider,
  parseOpenAIImage,
  parseGeminiImage,
  validatePrompt,
  type CoverProvider,
} from '@/lib/cover/image-generation';

const log = createLogger('api.cover.generate');

export const runtime = 'nodejs';
/** Image models are slow; well above the 30s default but inside Vercel's cap. */
export const maxDuration = 120;

const OPENAI_MODEL = 'gpt-image-1';
const GEMINI_MODEL = 'imagen-3.0-generate-002';
/** Providers can hang; without this the request would sit until maxDuration. */
const PROVIDER_TIMEOUT_MS = 90_000;

/**
 * GET — which providers are configured.
 *
 * Returns booleans only, never the keys or any prefix of them. The studio uses
 * this to decide what to offer and what setup hint to show.
 */
export async function GET() {
  const auth = await requireUser();
  if (!auth.ok) return auth.res;
  return NextResponse.json({ providers: availableProviders(process.env) });
}

/**
 * POST — generate a cover image and store it.
 *
 * Auth-gated because it spends real money per call: an open endpoint here is a
 * direct route to someone else's provider bill.
 *
 * The generated bytes are uploaded to R2 and only the resulting URL is
 * returned, so the studio treats a generated image exactly like an uploaded
 * one and nothing base64-sized crosses back over the wire.
 */
export async function POST(req: NextRequest) {
  try {
    const auth = await requireUser();
    if (!auth.ok) return auth.res;

    const body = await req.json().catch(() => null);
    if (!body || typeof body !== 'object') {
      return NextResponse.json({ error: 'Invalid request body.' }, { status: 400 });
    }

    const {
      prompt, provider: requestedProvider, style, palette, tags, avoid,
    } = body as {
      prompt?: unknown;
      provider?: CoverProvider;
      style?: string;
      palette?: string[];
      tags?: string[];
      avoid?: string;
    };

    const validated = validatePrompt(prompt);
    if (!validated.ok) {
      return NextResponse.json({ error: validated.error }, { status: 400 });
    }

    const resolved = resolveProvider(requestedProvider, availableProviders(process.env));
    if (!resolved.ok) {
      // 501: the request is valid, the server just isn't set up to serve it.
      return NextResponse.json({ error: resolved.error }, { status: 501 });
    }

    const fullPrompt = buildCoverPrompt({
      prompt: validated.prompt,
      style,
      palette: Array.isArray(palette) ? palette : undefined,
      tags: Array.isArray(tags) ? tags : undefined,
      avoid,
    });

    const generated = resolved.provider === 'openai'
      ? await generateOpenAI(fullPrompt)
      : await generateGemini(fullPrompt);

    if (!generated.ok) {
      log.warn('generation failed', { provider: resolved.provider, error: generated.error });
      return NextResponse.json({ error: generated.error }, { status: 502 });
    }

    const buffer = Buffer.from(generated.b64, 'base64');
    if (buffer.length === 0) {
      return NextResponse.json({ error: 'Provider returned an empty image.' }, { status: 502 });
    }

    const url = await uploadImage(buffer, 'png', 'image/png');
    log.info('cover generated', { provider: resolved.provider, bytes: buffer.length });

    return NextResponse.json({
      success: true,
      url,
      provider: resolved.provider,
      // Echoed so the studio can show exactly what was sent — the appended
      // constraints are otherwise invisible and make results hard to iterate on.
      prompt: fullPrompt,
    });
  } catch (err) {
    log.error('cover generate error', { error: errorMessage(err) });
    return NextResponse.json({ error: errorMessage(err) || 'Generation failed' }, { status: 500 });
  }
}

/** Fetch with a hard timeout, so a hung provider fails cleanly. */
async function fetchWithTimeout(url: string, init: RequestInit) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), PROVIDER_TIMEOUT_MS);
  try {
    return await fetch(url, { ...init, signal: ctrl.signal });
  } finally {
    clearTimeout(timer);
  }
}

type GenResult = { ok: true; b64: string } | { ok: false; error: string };

async function generateOpenAI(prompt: string): Promise<GenResult> {
  const key = process.env.OPENAI_API_KEY?.trim();
  if (!key) return { ok: false, error: 'OPENAI_API_KEY is not set.' };

  let res: Response;
  try {
    res = await fetchWithTimeout('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
      body: JSON.stringify({ model: OPENAI_MODEL, prompt, n: 1, size: '1024x1024' }),
    });
  } catch (err) {
    return { ok: false, error: `OpenAI request failed: ${errorMessage(err)}` };
  }

  const json = await res.json().catch(() => null);
  if (!res.ok) {
    const msg = (json as { error?: { message?: string } } | null)?.error?.message;
    return { ok: false, error: msg || `OpenAI returned ${res.status}.` };
  }
  return parseOpenAIImage(json);
}

async function generateGemini(prompt: string): Promise<GenResult> {
  const key = (process.env.GEMINI_API_KEY ?? process.env.GOOGLE_AI_API_KEY)?.trim();
  if (!key) return { ok: false, error: 'GEMINI_API_KEY is not set.' };

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:predict`;
  let res: Response;
  try {
    res = await fetchWithTimeout(url, {
      method: 'POST',
      // Key in a header, not the query string — query strings land in access
      // logs and proxy logs verbatim.
      headers: { 'Content-Type': 'application/json', 'x-goog-api-key': key },
      body: JSON.stringify({
        instances: [{ prompt }],
        parameters: { sampleCount: 1, aspectRatio: '1:1' },
      }),
    });
  } catch (err) {
    return { ok: false, error: `Gemini request failed: ${errorMessage(err)}` };
  }

  const json = await res.json().catch(() => null);
  if (!res.ok) {
    const msg = (json as { error?: { message?: string } } | null)?.error?.message;
    return { ok: false, error: msg || `Gemini returned ${res.status}.` };
  }
  return parseGeminiImage(json);
}
